name: base_project
description: A new Flutter project.
version: 0.0.1+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  build: 2.0.0
  # No nullsafety
  # get_version: 0.2.2
  # Helpers
  intl: 0.17.0
  logger: 0.9.4
  flutter_secure_storage: 4.1.0
  cross_connectivity: 3.0.1
  url_launcher: 6.0.2
  share: 2.0.1
  device_info_plus: 1.0.0
  websafe_platform: 1.2.0-nullsafety.0
  dartx: 0.7.0
  supercharged: 2.0.0
  # UI
  dio: ^4.0.0-prev3
  flutter_svg: 0.21.0-nullsafety.0
  google_fonts: 2.0.0
  cupertino_icons: 1.0.2
  carousel_slider: 3.0.0
  cached_network_image: 3.0.0-nullsafety
  flutter_screenutil: 5.0.0-nullsafety.10
  # Http & Generation
  pretty_dio_logger: 1.2.0-beta-1
  injectable: 1.2.2
  freezed_annotation: 0.14.1
  json_annotation: 4.0.1
  get_it: 6.0.0
  retrofit: 1.3.4+1
  auto_route: 1.0.2
  # Architecture
  flutter_bloc: 7.0.0
  rxdart: 0.26.0
  # Firebase
  # firebase_core: 0.5.0+1auto_route
  # firebase_messaging: 7.0.3
  # firebase_database: 4.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator:
    git:
      url: https://github.com/Chimerapps/retrofit.dart
      ref: master
      path: generator
  injectable_generator: 1.2.2
  flutter_launcher_icons: 0.9.0
  build_runner: 1.12.2
  freezed: 0.14.1+2
  json_serializable: 4.1.0
  auto_route_generator: 1.0.2
dependency_overrides:
  build_runner: 1.12.2
  json_serializable: 4.1.0
  analyzer: 1.3.0
  retrofit:
    git:
      url: https://github.com/Chimerapps/retrofit.dart
      ref: master
      path: annotation
flutter_icons:
  android: true
  ios: true
  image_path: "assets/png/mc_logo.png"
flutter:
  uses-material-design: true
  assets:
    - i18n/
    - assets/svg/loading.svg
    - assets/svgs/logo.svg
    - assets/svg/mc_logo.svg
    - assets/svg/close.svg
    - assets/svg/back_arrow.svg
    - assets/svg/handle.svg
    - assets/svg/another_catalog.svg
    - assets/svg/home.svg
    - assets/svg/logout.svg
    - assets/svg/settings.svg
    - assets/svg/switch.svg
    - assets/png/mc_logo.png
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/ubuntu/Ubuntu-Bold.ttf
        - asset: assets/ubuntu/Ubuntu-BoldItalic.ttf
          style: italic
        - asset: assets/ubuntu/Ubuntu-Italic.ttf
          style: italic
        - asset: assets/ubuntu/Ubuntu-Light.ttf
        - asset: assets/ubuntu/Ubuntu-LightItalic.ttf
          style: italic
        - asset: assets/ubuntu/Ubuntu-Medium.ttf
        - asset: assets/ubuntu/Ubuntu-MediumItalic.ttf
          style: italic
        - asset: assets/ubuntu/Ubuntu-Regular.ttf
targets:
  $default:
    builders:
      retrofit_generator|retrofit:
        enabled: true
        options:
          nullsafety: true